### ISSUE TITLE
ServiceServer node name

### ISSUE THREAD

**Issue by jrutgeer** [nirwester/ros2_journey_examples#1]
The ServiceServer node has name "service_client", also in the book text.

https://github.com/nirwester/ros2_journey_examples/blob/d5797ef0aeeaedf654532eb425448ac54bd46beb/callbacks_and_executors/src/service_server.cpp#L29-L30

**Comment by nirwester** [comment]
> The ServiceServer node has name "service_client", also in the book text.
> 
> https://github.com/nirwester/ros2_journey_examples/blob/d5797ef0aeeaedf654532eb425448ac54bd46beb/callbacks_and_executors/src/service_server.cpp#L29-L30

Thanks for the catch @jrutgeer !

**Comment by jrutgeer** [comment]
There's another copy paste error in the comment :-)

https://github.com/nirwester/ros2_journey_examples/blob/e8ebd5e156d80747709d4d8e2aa87a0a02d851c9/callbacks_and_executors/include/service_test_pkg/service_client.hpp#L30-L33

</br>

Small remark wrt. this example in the book: 

It states: "If we associate each of these nodes to a single threaded executor and
launch them, we’ll get the following output:
```
[INFO] [1677174288.191074237] [service_server]: Service started
[INFO] [1677174288.201386702] [service_client]: Client started
[INFO] [1677174288.701485575] [service_client]: Sending request
[INFO] [1677174288.701628262] [service_client]: Got a request
```

To me, this was confusing, since I interpreted above sentence as "If we associate each of these nodes to **one** single threaded executor", in which case you obviously don't get the "Got a request":
```
[INFO] [1677174288.191074237] [service_server]: Service started
[INFO] [1677174288.201386702] [service_client]: Client started
[INFO] [1677174288.701485575] [service_client]: Sending request
```

Overall congrats on the book!

**Comment by nirwester** [comment]
Thanks a lot for the correction and the tip, I'll make that statement a bit less ambiguous :)
